export GOVC_URL='10.0.88.201'
export GOVC_USERNAME='Administrator@vclab.local'
export GOVC_PASSWORD='gsL@B!234!Q'
export GOVC_INSECURE=true


################################################################
# this command is working fine 
# govc vm.change -e="guestinfo.ignition.config.data.encoding=base64" -vm='test-vc-ocp-bootstrap'

# govc vm.change -e="disk.EnableUUID=TRUE" -vm='test-vc-ocp-bootstrap'

# govc vm.change -e="guestinfo.ignition.config.data=ewoiaWduaXRpb24iOiB7CiAgICAiY29uZmlnIjogewogICAgIm1lcmdlIjogWwogICAgICAgIHsKICAgICAgICAic291cmNlIjogImh0dHA6Ly8xMC4xMzYuNTYuMzg6ODA4MS9ib290c3RyYXAuaWduIiAKICAgICAgICB9CiAgICBdCiAgICB9LAogICAgInZlcnNpb24iOiAiMy4xLjAiCiAgfQp9" -vm='test-vc-ocp-bootstrap'

# export IPCFG="ip=10.136.56.36.::10.136.0.1:255.255.255.0:test-vc-ocp-bootstrap.gslab.ocp.local.:ens192:none nameserver=10.136.56.38"

# govc vm.change -vm "test-vc-ocp-bootstrap" -e "guestinfo.afterburn.initrd.network-kargs=${IPCFG}"

# govc vm.power -on test-vc-ocp-bootstrap

################################################################

################################################################
# working fine for master-3
# govc vm.change -e="guestinfo.ignition.config.data.encoding=base64" -vm='test-vc-ocp-master-3'

# govc vm.change -e="disk.EnableUUID=TRUE" -vm='test-vc-ocp-master-3'

# govc vm.change -e="guestinfo.ignition.config.data=eyJpZ25pdGlvbiI6eyJjb25maWciOnsibWVyZ2UiOlt7InNvdXJjZSI6Imh0dHBzOi8vYXBpLWludC5nc2xhYi5vY3AubG9jYWw6MjI2MjMvY29uZmlnL21hc3RlciJ9XX0sInNlY3VyaXR5Ijp7InRscyI6eyJjZXJ0aWZpY2F0ZUF1dGhvcml0aWVzIjpbeyJzb3VyY2UiOiJkYXRhOnRleHQvcGxhaW47Y2hhcnNldD11dGYtODtiYXNlNjQsTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkZSRU5EUVdacFowRjNTVUpCWjBsSlRrOVBNM05hT0ZGcUszTjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRWGRLYWtWVFRVSkJSMEV4VlVVS1EzaE5TbUl6UW14aWJrNXZZVmRhTUUxU1FYZEVaMWxFVmxGUlJFVjNaSGxpTWprd1RGZE9hRTFDTkZoRVZFbDRUVVJSZUU1RVFUTk5WRVV4VFd4dldBcEVWRTE0VFVSUmVFMXFRVE5OVkVVeFRXeHZkMHBxUlZOTlFrRkhRVEZWUlVONFRVcGlNMEpzWW01T2IyRlhXakJOVWtGM1JHZFpSRlpSVVVSRmQyUjVDbUl5T1RCTVYwNW9UVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRXdZVWhrVEhkaGR6YzJlazhLZUVKcFVWVkdibTFQY25oU2FTOVRWMnRXVEVNMVRVMXlSR1o1Tnk5MmQzUkdiRlEyTm5NNUwweDZjVFZtVVhFMlVpOXVRa3Q2YmxsMWNGWXdiM1VyVEFwbVkyTnZlbk5EVVVOdGNEUjZkMnBHVkZCNU1EQXlRbGswYUcxUU1uSXpabUpOUm1RdmJrOXdhazB5TW10REwxcEVjM3BYZHk5S1NuVlRZV1U0VmxVMENubHJaMFptVjNVeGJGTTVhMVJJUkhaNmMxbG9Obmt2TWt0b2VUSm9XVlkxTjNwWVZVaGxRbE5HTWtGMWFVMVNWMFZRTUhsRUwzZFFkVTh2U3pSbWJHTUtjR0ptUm0wclMwOHhURUpLV21sQk5WRkVMMUJPYmxwdFUzcG1TWGh5V2psclRtMDBiM0ZpT1ZGYVRXTm9jRU5MU1VsRWJWUmFXWFkwUW1WdFFXSXlXZ3BaV2tkcVJYWlpNVTFzUkRnMFMwSXJWalF4TDBKbFlXeGpZVkZGTDJGWE1tZEdlQ3R3YzB4dk5IWkhUVkl6UkhWd01XTnFTak16UzFSUFJUbFlSMnBTQ2xkSmMwMWhURmQzUVhkSlJFRlJRVUp2TUVsM1VVUkJUMEpuVGxaSVVUaENRV1k0UlVKQlRVTkJjVkYzUkhkWlJGWlNNRlJCVVVndlFrRlZkMEYzUlVJS0wzcEJaRUpuVGxaSVVUUkZSbWRSVldoRVYweGtOV2xHWVd4NVJtRjJNRTFKY21KMVMwczNOMVk0WjNkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJBcG5aMFZDUVVkNFRqbGhhVGxMYUN0MlkzbE9VbEl4UVU4NWIxRmhURXRNVFRSU2VGUTJkRWw2YTNCc0wwUmpVbmRyTUhObksyVklUM05rY20xTWVXZDNDbXcxV1VZMVoxbHZSR2xZZFRBNGRGVXJlQ3N2UTBKbmJrUlhkMGRhTm5GRVIzbHpOWEJ4VjIxaldUVlVNRVV5YlRoMFFVZEZORkV3YldnMWRqQmpjVk1LUkRWMlNtVXZhMDVNVDFGamFreHZLMmRDZDBKMGIwUkZaakZCT0hWWVJYTjRUVVJKUTJSd2NHcENiMVYyVFVWdGNHeFNha051ZUhVdk5VdGxVVzE1V1FweU5tbFBNMVJxZVU5SVpFc3JNV2xyVFZGVlIwVk9MMnRXTDFadWQyNWhlV05EU2xKdldETlFka05MUzBadk15OHJhMDV6U25FNWJtcHFRMXBNVkV4R0NteDFVQ3RFWVVaVk1tUktZVk5NVjJNeVNTOURhRE5EWlhCRWIyNUtURUZGTW1adE5UaDNSRUY0T1hwNlNXNXBNRWhVVlZOWldDdGxkWFZNUjJKRWJDOEtaMnhaUkRGMVkwUTRXV3BvVWxoelFXazRWR2xHWlVSSVpXWmpQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09In1dfX0sInZlcnNpb24iOiIzLjEuMCJ9fQ==" -vm='test-vc-ocp-master-3'

# export IPCFG="ip=10.136.56.33::10.136.0.1:255.255.255.0:master-3.gslab.ocp.local:ens192:none nameserver=10.136.56.38"

# govc vm.change -vm "test-vc-ocp-master-3" -e "guestinfo.afterburn.initrd.network-kargs=${IPCFG}"

# govc vm.power -on test-vc-ocp-master-3
################################################################


################################################################
# working fine for master-2 tested 
# govc vm.change -e="guestinfo.ignition.config.data.encoding=base64" -vm='test-vc-ocp-master-2'

# govc vm.change -e="disk.EnableUUID=TRUE" -vm='test-vc-ocp-master-2'

# govc vm.change -e="guestinfo.ignition.config.data=eyJpZ25pdGlvbiI6eyJjb25maWciOnsibWVyZ2UiOlt7InNvdXJjZSI6Imh0dHBzOi8vYXBpLWludC5nc2xhYi5vY3AubG9jYWw6MjI2MjMvY29uZmlnL21hc3RlciJ9XX0sInNlY3VyaXR5Ijp7InRscyI6eyJjZXJ0aWZpY2F0ZUF1dGhvcml0aWVzIjpbeyJzb3VyY2UiOiJkYXRhOnRleHQvcGxhaW47Y2hhcnNldD11dGYtODtiYXNlNjQsTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkZSRU5EUVdacFowRjNTVUpCWjBsSlRrOVBNM05hT0ZGcUszTjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRWGRLYWtWVFRVSkJSMEV4VlVVS1EzaE5TbUl6UW14aWJrNXZZVmRhTUUxU1FYZEVaMWxFVmxGUlJFVjNaSGxpTWprd1RGZE9hRTFDTkZoRVZFbDRUVVJSZUU1RVFUTk5WRVV4VFd4dldBcEVWRTE0VFVSUmVFMXFRVE5OVkVVeFRXeHZkMHBxUlZOTlFrRkhRVEZWUlVONFRVcGlNMEpzWW01T2IyRlhXakJOVWtGM1JHZFpSRlpSVVVSRmQyUjVDbUl5T1RCTVYwNW9UVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRXdZVWhrVEhkaGR6YzJlazhLZUVKcFVWVkdibTFQY25oU2FTOVRWMnRXVEVNMVRVMXlSR1o1Tnk5MmQzUkdiRlEyTm5NNUwweDZjVFZtVVhFMlVpOXVRa3Q2YmxsMWNGWXdiM1VyVEFwbVkyTnZlbk5EVVVOdGNEUjZkMnBHVkZCNU1EQXlRbGswYUcxUU1uSXpabUpOUm1RdmJrOXdhazB5TW10REwxcEVjM3BYZHk5S1NuVlRZV1U0VmxVMENubHJaMFptVjNVeGJGTTVhMVJJUkhaNmMxbG9Obmt2TWt0b2VUSm9XVlkxTjNwWVZVaGxRbE5HTWtGMWFVMVNWMFZRTUhsRUwzZFFkVTh2U3pSbWJHTUtjR0ptUm0wclMwOHhURUpLV21sQk5WRkVMMUJPYmxwdFUzcG1TWGh5V2psclRtMDBiM0ZpT1ZGYVRXTm9jRU5MU1VsRWJWUmFXWFkwUW1WdFFXSXlXZ3BaV2tkcVJYWlpNVTFzUkRnMFMwSXJWalF4TDBKbFlXeGpZVkZGTDJGWE1tZEdlQ3R3YzB4dk5IWkhUVkl6UkhWd01XTnFTak16UzFSUFJUbFlSMnBTQ2xkSmMwMWhURmQzUVhkSlJFRlJRVUp2TUVsM1VVUkJUMEpuVGxaSVVUaENRV1k0UlVKQlRVTkJjVkYzUkhkWlJGWlNNRlJCVVVndlFrRlZkMEYzUlVJS0wzcEJaRUpuVGxaSVVUUkZSbWRSVldoRVYweGtOV2xHWVd4NVJtRjJNRTFKY21KMVMwczNOMVk0WjNkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJBcG5aMFZDUVVkNFRqbGhhVGxMYUN0MlkzbE9VbEl4UVU4NWIxRmhURXRNVFRSU2VGUTJkRWw2YTNCc0wwUmpVbmRyTUhObksyVklUM05rY20xTWVXZDNDbXcxV1VZMVoxbHZSR2xZZFRBNGRGVXJlQ3N2UTBKbmJrUlhkMGRhTm5GRVIzbHpOWEJ4VjIxaldUVlVNRVV5YlRoMFFVZEZORkV3YldnMWRqQmpjVk1LUkRWMlNtVXZhMDVNVDFGamFreHZLMmRDZDBKMGIwUkZaakZCT0hWWVJYTjRUVVJKUTJSd2NHcENiMVYyVFVWdGNHeFNha051ZUhVdk5VdGxVVzE1V1FweU5tbFBNMVJxZVU5SVpFc3JNV2xyVFZGVlIwVk9MMnRXTDFadWQyNWhlV05EU2xKdldETlFka05MUzBadk15OHJhMDV6U25FNWJtcHFRMXBNVkV4R0NteDFVQ3RFWVVaVk1tUktZVk5NVjJNeVNTOURhRE5EWlhCRWIyNUtURUZGTW1adE5UaDNSRUY0T1hwNlNXNXBNRWhVVlZOWldDdGxkWFZNUjJKRWJDOEtaMnhaUkRGMVkwUTRXV3BvVWxoelFXazRWR2xHWlVSSVpXWmpQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09In1dfX0sInZlcnNpb24iOiIzLjEuMCJ9fQ==" -vm='test-vc-ocp-master-2'

# export IPCFG="ip=10.136.56.32::10.136.0.1:255.255.255.0:master-2.gslab.ocp.local:ens192:none nameserver=10.136.56.38"

# govc vm.change -vm "test-vc-ocp-master-2" -e "guestinfo.afterburn.initrd.network-kargs=${IPCFG}"

# govc vm.power -on test-vc-ocp-master-2
################################################################

################################################################
# working fine for master-1

# govc vm.change -e="guestinfo.ignition.config.data.encoding=base64" -vm='test-vc-ocp-master-1'

# govc vm.change -e="disk.EnableUUID=TRUE" -vm='test-vc-ocp-master-1'

# govc vm.change -e="guestinfo.ignition.config.data=eyJpZ25pdGlvbiI6eyJjb25maWciOnsibWVyZ2UiOlt7InNvdXJjZSI6Imh0dHBzOi8vYXBpLWludC5nc2xhYi5vY3AubG9jYWw6MjI2MjMvY29uZmlnL21hc3RlciJ9XX0sInNlY3VyaXR5Ijp7InRscyI6eyJjZXJ0aWZpY2F0ZUF1dGhvcml0aWVzIjpbeyJzb3VyY2UiOiJkYXRhOnRleHQvcGxhaW47Y2hhcnNldD11dGYtODtiYXNlNjQsTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkZSRU5EUVdacFowRjNTVUpCWjBsSlRrOVBNM05hT0ZGcUszTjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRWGRLYWtWVFRVSkJSMEV4VlVVS1EzaE5TbUl6UW14aWJrNXZZVmRhTUUxU1FYZEVaMWxFVmxGUlJFVjNaSGxpTWprd1RGZE9hRTFDTkZoRVZFbDRUVVJSZUU1RVFUTk5WRVV4VFd4dldBcEVWRTE0VFVSUmVFMXFRVE5OVkVVeFRXeHZkMHBxUlZOTlFrRkhRVEZWUlVONFRVcGlNMEpzWW01T2IyRlhXakJOVWtGM1JHZFpSRlpSVVVSRmQyUjVDbUl5T1RCTVYwNW9UVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRXdZVWhrVEhkaGR6YzJlazhLZUVKcFVWVkdibTFQY25oU2FTOVRWMnRXVEVNMVRVMXlSR1o1Tnk5MmQzUkdiRlEyTm5NNUwweDZjVFZtVVhFMlVpOXVRa3Q2YmxsMWNGWXdiM1VyVEFwbVkyTnZlbk5EVVVOdGNEUjZkMnBHVkZCNU1EQXlRbGswYUcxUU1uSXpabUpOUm1RdmJrOXdhazB5TW10REwxcEVjM3BYZHk5S1NuVlRZV1U0VmxVMENubHJaMFptVjNVeGJGTTVhMVJJUkhaNmMxbG9Obmt2TWt0b2VUSm9XVlkxTjNwWVZVaGxRbE5HTWtGMWFVMVNWMFZRTUhsRUwzZFFkVTh2U3pSbWJHTUtjR0ptUm0wclMwOHhURUpLV21sQk5WRkVMMUJPYmxwdFUzcG1TWGh5V2psclRtMDBiM0ZpT1ZGYVRXTm9jRU5MU1VsRWJWUmFXWFkwUW1WdFFXSXlXZ3BaV2tkcVJYWlpNVTFzUkRnMFMwSXJWalF4TDBKbFlXeGpZVkZGTDJGWE1tZEdlQ3R3YzB4dk5IWkhUVkl6UkhWd01XTnFTak16UzFSUFJUbFlSMnBTQ2xkSmMwMWhURmQzUVhkSlJFRlJRVUp2TUVsM1VVUkJUMEpuVGxaSVVUaENRV1k0UlVKQlRVTkJjVkYzUkhkWlJGWlNNRlJCVVVndlFrRlZkMEYzUlVJS0wzcEJaRUpuVGxaSVVUUkZSbWRSVldoRVYweGtOV2xHWVd4NVJtRjJNRTFKY21KMVMwczNOMVk0WjNkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJBcG5aMFZDUVVkNFRqbGhhVGxMYUN0MlkzbE9VbEl4UVU4NWIxRmhURXRNVFRSU2VGUTJkRWw2YTNCc0wwUmpVbmRyTUhObksyVklUM05rY20xTWVXZDNDbXcxV1VZMVoxbHZSR2xZZFRBNGRGVXJlQ3N2UTBKbmJrUlhkMGRhTm5GRVIzbHpOWEJ4VjIxaldUVlVNRVV5YlRoMFFVZEZORkV3YldnMWRqQmpjVk1LUkRWMlNtVXZhMDVNVDFGamFreHZLMmRDZDBKMGIwUkZaakZCT0hWWVJYTjRUVVJKUTJSd2NHcENiMVYyVFVWdGNHeFNha051ZUhVdk5VdGxVVzE1V1FweU5tbFBNMVJxZVU5SVpFc3JNV2xyVFZGVlIwVk9MMnRXTDFadWQyNWhlV05EU2xKdldETlFka05MUzBadk15OHJhMDV6U25FNWJtcHFRMXBNVkV4R0NteDFVQ3RFWVVaVk1tUktZVk5NVjJNeVNTOURhRE5EWlhCRWIyNUtURUZGTW1adE5UaDNSRUY0T1hwNlNXNXBNRWhVVlZOWldDdGxkWFZNUjJKRWJDOEtaMnhaUkRGMVkwUTRXV3BvVWxoelFXazRWR2xHWlVSSVpXWmpQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09In1dfX0sInZlcnNpb24iOiIzLjEuMCJ9fQ==" -vm='test-vc-ocp-master-1'

# export IPCFG="ip=10.136.56.31::10.136.0.1:255.255.255.0:master-1.gslab.ocp.local:ens192:none nameserver=10.136.56.38"

# govc vm.change -vm "test-vc-ocp-master-1" -e "guestinfo.afterburn.initrd.network-kargs=${IPCFG}"

# govc vm.power -on test-vc-ocp-master-1
################################################################


################################################################
#  working fine for worker-1
# govc vm.change -e="guestinfo.ignition.config.data.encoding=base64" -vm='test-vc-ocp-worker-1'

# govc vm.change -e="disk.EnableUUID=TRUE" -vm='test-vc-ocp-worker-1'

# govc vm.change -e="guestinfo.ignition.config.data=eyJpZ25pdGlvbiI6eyJjb25maWciOnsibWVyZ2UiOlt7InNvdXJjZSI6Imh0dHBzOi8vYXBpLWludC5nc2xhYi5vY3AubG9jYWw6MjI2MjMvY29uZmlnL21hc3RlciJ9XX0sInNlY3VyaXR5Ijp7InRscyI6eyJjZXJ0aWZpY2F0ZUF1dGhvcml0aWVzIjpbeyJzb3VyY2UiOiJkYXRhOnRleHQvcGxhaW47Y2hhcnNldD11dGYtODtiYXNlNjQsTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkZSRU5EUVdacFowRjNTVUpCWjBsSlRrOVBNM05hT0ZGcUszTjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRWGRLYWtWVFRVSkJSMEV4VlVVS1EzaE5TbUl6UW14aWJrNXZZVmRhTUUxU1FYZEVaMWxFVmxGUlJFVjNaSGxpTWprd1RGZE9hRTFDTkZoRVZFbDRUVVJSZUU1RVFUTk5WRVV4VFd4dldBcEVWRTE0VFVSUmVFMXFRVE5OVkVVeFRXeHZkMHBxUlZOTlFrRkhRVEZWUlVONFRVcGlNMEpzWW01T2IyRlhXakJOVWtGM1JHZFpSRlpSVVVSRmQyUjVDbUl5T1RCTVYwNW9UVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRXdZVWhrVEhkaGR6YzJlazhLZUVKcFVWVkdibTFQY25oU2FTOVRWMnRXVEVNMVRVMXlSR1o1Tnk5MmQzUkdiRlEyTm5NNUwweDZjVFZtVVhFMlVpOXVRa3Q2YmxsMWNGWXdiM1VyVEFwbVkyTnZlbk5EVVVOdGNEUjZkMnBHVkZCNU1EQXlRbGswYUcxUU1uSXpabUpOUm1RdmJrOXdhazB5TW10REwxcEVjM3BYZHk5S1NuVlRZV1U0VmxVMENubHJaMFptVjNVeGJGTTVhMVJJUkhaNmMxbG9Obmt2TWt0b2VUSm9XVlkxTjNwWVZVaGxRbE5HTWtGMWFVMVNWMFZRTUhsRUwzZFFkVTh2U3pSbWJHTUtjR0ptUm0wclMwOHhURUpLV21sQk5WRkVMMUJPYmxwdFUzcG1TWGh5V2psclRtMDBiM0ZpT1ZGYVRXTm9jRU5MU1VsRWJWUmFXWFkwUW1WdFFXSXlXZ3BaV2tkcVJYWlpNVTFzUkRnMFMwSXJWalF4TDBKbFlXeGpZVkZGTDJGWE1tZEdlQ3R3YzB4dk5IWkhUVkl6UkhWd01XTnFTak16UzFSUFJUbFlSMnBTQ2xkSmMwMWhURmQzUVhkSlJFRlJRVUp2TUVsM1VVUkJUMEpuVGxaSVVUaENRV1k0UlVKQlRVTkJjVkYzUkhkWlJGWlNNRlJCVVVndlFrRlZkMEYzUlVJS0wzcEJaRUpuVGxaSVVUUkZSbWRSVldoRVYweGtOV2xHWVd4NVJtRjJNRTFKY21KMVMwczNOMVk0WjNkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJBcG5aMFZDUVVkNFRqbGhhVGxMYUN0MlkzbE9VbEl4UVU4NWIxRmhURXRNVFRSU2VGUTJkRWw2YTNCc0wwUmpVbmRyTUhObksyVklUM05rY20xTWVXZDNDbXcxV1VZMVoxbHZSR2xZZFRBNGRGVXJlQ3N2UTBKbmJrUlhkMGRhTm5GRVIzbHpOWEJ4VjIxaldUVlVNRVV5YlRoMFFVZEZORkV3YldnMWRqQmpjVk1LUkRWMlNtVXZhMDVNVDFGamFreHZLMmRDZDBKMGIwUkZaakZCT0hWWVJYTjRUVVJKUTJSd2NHcENiMVYyVFVWdGNHeFNha051ZUhVdk5VdGxVVzE1V1FweU5tbFBNMVJxZVU5SVpFc3JNV2xyVFZGVlIwVk9MMnRXTDFadWQyNWhlV05EU2xKdldETlFka05MUzBadk15OHJhMDV6U25FNWJtcHFRMXBNVkV4R0NteDFVQ3RFWVVaVk1tUktZVk5NVjJNeVNTOURhRE5EWlhCRWIyNUtURUZGTW1adE5UaDNSRUY0T1hwNlNXNXBNRWhVVlZOWldDdGxkWFZNUjJKRWJDOEtaMnhaUkRGMVkwUTRXV3BvVWxoelFXazRWR2xHWlVSSVpXWmpQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09In1dfX0sInZlcnNpb24iOiIzLjEuMCJ9fQ==" -vm='test-vc-ocp-worker-1'

# export IPCFG="ip=10.136.56.34::10.136.0.1:255.255.255.0:worker-1.gslab.ocp.local:ens192:none nameserver=10.136.56.38"

# govc vm.change -vm "test-vc-ocp-worker-1" -e "guestinfo.afterburn.initrd.network-kargs=${IPCFG}"

# govc vm.power -on test-vc-ocp-worker-1

################################################################


govc vm.change -e="guestinfo.ignition.config.data.encoding=base64" -vm='test-vc-ocp-worker-2'

govc vm.change -e="disk.EnableUUID=TRUE" -vm='test-vc-ocp-worker-2'

govc vm.change -e="guestinfo.ignition.config.data=eyJpZ25pdGlvbiI6eyJjb25maWciOnsibWVyZ2UiOlt7InNvdXJjZSI6Imh0dHBzOi8vYXBpLWludC5nc2xhYi5vY3AubG9jYWw6MjI2MjMvY29uZmlnL21hc3RlciJ9XX0sInNlY3VyaXR5Ijp7InRscyI6eyJjZXJ0aWZpY2F0ZUF1dGhvcml0aWVzIjpbeyJzb3VyY2UiOiJkYXRhOnRleHQvcGxhaW47Y2hhcnNldD11dGYtODtiYXNlNjQsTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkZSRU5EUVdacFowRjNTVUpCWjBsSlRrOVBNM05hT0ZGcUszTjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRWGRLYWtWVFRVSkJSMEV4VlVVS1EzaE5TbUl6UW14aWJrNXZZVmRhTUUxU1FYZEVaMWxFVmxGUlJFVjNaSGxpTWprd1RGZE9hRTFDTkZoRVZFbDRUVVJSZUU1RVFUTk5WRVV4VFd4dldBcEVWRTE0VFVSUmVFMXFRVE5OVkVVeFRXeHZkMHBxUlZOTlFrRkhRVEZWUlVONFRVcGlNMEpzWW01T2IyRlhXakJOVWtGM1JHZFpSRlpSVVVSRmQyUjVDbUl5T1RCTVYwNW9UVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRXdZVWhrVEhkaGR6YzJlazhLZUVKcFVWVkdibTFQY25oU2FTOVRWMnRXVEVNMVRVMXlSR1o1Tnk5MmQzUkdiRlEyTm5NNUwweDZjVFZtVVhFMlVpOXVRa3Q2YmxsMWNGWXdiM1VyVEFwbVkyTnZlbk5EVVVOdGNEUjZkMnBHVkZCNU1EQXlRbGswYUcxUU1uSXpabUpOUm1RdmJrOXdhazB5TW10REwxcEVjM3BYZHk5S1NuVlRZV1U0VmxVMENubHJaMFptVjNVeGJGTTVhMVJJUkhaNmMxbG9Obmt2TWt0b2VUSm9XVlkxTjNwWVZVaGxRbE5HTWtGMWFVMVNWMFZRTUhsRUwzZFFkVTh2U3pSbWJHTUtjR0ptUm0wclMwOHhURUpLV21sQk5WRkVMMUJPYmxwdFUzcG1TWGh5V2psclRtMDBiM0ZpT1ZGYVRXTm9jRU5MU1VsRWJWUmFXWFkwUW1WdFFXSXlXZ3BaV2tkcVJYWlpNVTFzUkRnMFMwSXJWalF4TDBKbFlXeGpZVkZGTDJGWE1tZEdlQ3R3YzB4dk5IWkhUVkl6UkhWd01XTnFTak16UzFSUFJUbFlSMnBTQ2xkSmMwMWhURmQzUVhkSlJFRlJRVUp2TUVsM1VVUkJUMEpuVGxaSVVUaENRV1k0UlVKQlRVTkJjVkYzUkhkWlJGWlNNRlJCVVVndlFrRlZkMEYzUlVJS0wzcEJaRUpuVGxaSVVUUkZSbWRSVldoRVYweGtOV2xHWVd4NVJtRjJNRTFKY21KMVMwczNOMVk0WjNkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJBcG5aMFZDUVVkNFRqbGhhVGxMYUN0MlkzbE9VbEl4UVU4NWIxRmhURXRNVFRSU2VGUTJkRWw2YTNCc0wwUmpVbmRyTUhObksyVklUM05rY20xTWVXZDNDbXcxV1VZMVoxbHZSR2xZZFRBNGRGVXJlQ3N2UTBKbmJrUlhkMGRhTm5GRVIzbHpOWEJ4VjIxaldUVlVNRVV5YlRoMFFVZEZORkV3YldnMWRqQmpjVk1LUkRWMlNtVXZhMDVNVDFGamFreHZLMmRDZDBKMGIwUkZaakZCT0hWWVJYTjRUVVJKUTJSd2NHcENiMVYyVFVWdGNHeFNha051ZUhVdk5VdGxVVzE1V1FweU5tbFBNMVJxZVU5SVpFc3JNV2xyVFZGVlIwVk9MMnRXTDFadWQyNWhlV05EU2xKdldETlFka05MUzBadk15OHJhMDV6U25FNWJtcHFRMXBNVkV4R0NteDFVQ3RFWVVaVk1tUktZVk5NVjJNeVNTOURhRE5EWlhCRWIyNUtURUZGTW1adE5UaDNSRUY0T1hwNlNXNXBNRWhVVlZOWldDdGxkWFZNUjJKRWJDOEtaMnhaUkRGMVkwUTRXV3BvVWxoelFXazRWR2xHWlVSSVpXWmpQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09In1dfX0sInZlcnNpb24iOiIzLjEuMCJ9fQ==" -vm='test-vc-ocp-worker-2'

export IPCFG="ip=10.136.56.35::10.136.0.1:255.255.255.0:worker-2.gslab.ocp.local:ens192:none nameserver=10.136.56.38"

govc vm.change -vm "test-vc-ocp-worker-2" -e "guestinfo.afterburn.initrd.network-kargs=${IPCFG}"

govc vm.power -on test-vc-ocp-worker-2

